export const FETCH_BERITA_START = 'FETCH_BERITA_START';
export const FETCH_BERITA_SUCCESS = 'FETCH_BERITA_SUCCESS';

export const FETCH_SINGLE_BERITA_START = 'FETCH_SINGLE_BERITA_START';
export const FETCH_SINGLE_BERITA_SUCCESS = 'FETCH_SINGLE_BERITA_SUCCESS';
export const FETCH_SINGLE_BERITA_FAIL = 'FETCH_SINGLE_BERITA_FAIL';

export const DAFTAR_BARU_START = 'DAFTAR_BARU_START';
export const DAFTAR_BARU_SUCCESS = 'DAFTAR_BARU_SUCCESS';
export const DAFTAR_BARU_FAIL = 'DAFTAR_BARU_FAIL';

export const FETCH_IMAGE_GALLERY_START = 'FETCH_IMAGE_GALLERY_START';
export const FETCH_IMAGE_GALLERY_SUCCESS = 'FETCH_IMAGE_GALLERY_SUCCESS';

export const RESET_ERROR_PENDAFTARAN = 'RESET_ERROR_PENDAFTARAN';
export const MODAL_TOGGLER_HANDLER = 'MODAL_TOGGLER_HANDLER';